universityofcalifornia/NeXt

app/models/user.rb
app/views/users/show.erb

add format to include user suffix to user model. In user show view, use suffix format with display_name and add position.description

Issue #54 Add missing fields to user show view (people profile detail page)

---

.gitignore
.rspec
.travis.yml
Gemfile
Gemfile.lock
app/controllers/invites_controller.rb
app/mailers/event_notifier.rb
app/models/event.rb
app/models/invite.rb
app/views/event_notifier/notify_invite.html.erb
config/environments/development.rb
config/environments/test.rb
config/initializers/task_scheduler.rb
config/routes.rb
db/migrate/20150610195345_add_responded_to_invites.rb
db/schema.rb
spec/factories/event.rb
spec/factories/invite.rb
spec/features/log_in_spec.rb
spec/mailers/event_notifier_spec.rb
spec/mailers/previews/event_notifier_preview.rb
spec/models/event_spec.rb
spec/models/invite_spec.rb
spec/rails_helper.rb

I implemented rufus scheduler for now to deliver emails.

Email invites

---

app/controllers/ideas/votes_controller.rb
app/controllers/projects/votes_controller.rb
app/models/idea.rb
app/models/project.rb
app/views/projects/_form.erb
app/views/projects/show.erb
db/seeds/project_statuses.rb
db/seeds/users.rb

Update to incorporate @chabgood 's suggestions.

Issue #69 - Refactor idea/project votes to put more logic in models

---

Gemfile

removed the ruby 2.1.5 entry in gemfile

removed the ruby 2.1.5 entry in gemfile

---

app/controllers/auth/local/registration_controller.rb
app/views/auth/local/registration/new.html.erb
db/schema.rb

This pull request adds a page where you can create local accounts (per request from @rrocchio).
Ignore the bit in schema.rb about badges. The file simply wasn't committed by whomever made that migration when that migration was added, hence why it shows up now.

Add basic ability to create a local account

---

Blockfile.rb
app/controllers/application_controller.rb
app/controllers/invites_controller.rb
app/helpers/application_helper.rb
app/views/badges/index.html.erb
app/views/badges/show.html.erb
app/views/events/show.html.erb
app/views/groups/_new_group.html.erb
app/views/ideas/index.html.erb
app/views/ideas/show.html.erb
app/views/layouts/application.html.erb
app/views/projects/_form.html.erb
app/views/projects/documents/index.html.erb
app/views/projects/index.html.erb
app/views/projects/show.html.erb
app/views/shared/_vote_dialog.html.erb
app/views/users/show.html.erb
blocks/bootstrap/_buttons.scss
blocks/bootstrap/_forms.scss
blocks/bootstrap/_list-group.scss
blocks/bootstrap/_panels.scss
blocks/config/_variables.scss
blocks/site/_base.scss

See issue #139 for some guidelines on utilizing the new CSS.

Issue #139 - CSS for new design

---

app/controllers/events_controller.rb
app/models/event.rb
app/views/events/_form.html.erb
app/views/events/show.html.erb

This pull request makes the following changes to events:
* fixes #147 so submit button is no longer disabled on edit
* fixes #148 so end date datetimepicker is applied correctly
* fix bug with start/end date not being applied to datetimepicker
* fix bug with `#create` and `#update` not accepting correct end date name
* modify description to be a WYSIWYG editor
* improve basic presentation of events

Fixes to Events

---

Blockfile.rb
app/controllers/groups_controller.rb
app/models/group.rb
app/views/groups/_form.html.erb
app/views/groups/_user_group_link_count.html.erb
app/views/groups/edit.html.erb
app/views/groups/index.html.erb
app/views/groups/new.html.erb
app/views/groups/show.html.erb

This pull request adds basic create-read-update-delete operations for groups, like managing other assets. I did not change the data model in this pull request. That will be adjusted in a future pull request to meet with the feature request in #151.

Add basic CRUD for groups

---

app/controllers/events_controller.rb
app/models/badge.rb
app/models/organization.rb
app/views/badges/index.html.erb
app/views/competencies/index.html.erb
app/views/events/index.html.erb
app/views/layouts/components/_topbar.html.erb
app/views/local/users/index.html.erb
app/views/projects/documents/index.html.erb
app/views/projects/index.html.erb
app/views/shared/_engagement_meter.html.erb
app/views/shared/_nav.html.erb
app/views/users/badges/index.html.erb
blocks/site/_header.scss
db/migrate/20150814180616_unescape_anr.rb
db/migrate/20150814222150_add_engagement_meter_display_to_organizations.rb
db/schema.rb
db/seeds/organizations.rb

I'm not done working today, but I'll be out from 4 until 7 or 8. I'll do a couple more hours tonight (Aug 14). If anyone wants to work on stuff, feel free to merge this. Otherwise I'll just keep committing and they will get applied with this pull request.

Various small issues

---

db/migrate/20150902173611_add_osx_to_competencies.rb
db/schema.rb

only 1 change: use migration to add record to competencies

Add osx to competencies 218

---

.travis.yml
app/controllers/ideas/votes_controller.rb
app/models/idea.rb
app/views/ideas/show.html.erb
config/routes.rb
db/migrate/20150814180616_unescape_anr.rb
db/migrate/20150902220120_add_index_to_idea_votes_idea_id.rb
db/schema.rb

change includes index on idea_votes.idea_id.

code is fix for issue 55. allows user to change or withdraw votes for an idea 

---

app/controllers/competencies_controller.rb
app/controllers/users_controller.rb
app/views/users/_form.html.erb
config/routes.rb

implement suggestion in issue #219 from @spiritcapsule using same auto complete functionality for groups in events page

replace competency select box with autocomplete (jquery-tokeninput)

---

app/controllers/competencies_controller.rb
app/controllers/users_controller.rb
app/views/events/_form.html.erb
app/views/users/_form.html.erb
config/routes.rb

the prePopulate method of tokenInput was expecting JSON

Fix event edit missing groups 237

---

app/views/shared/_engagement_meter.html.erb

I committed to the wrong branch on my forked repo, please ignore the 'twitter-feed' business. ;-)

Issue #123 - Show organization's points when hovering over bars on engagement meter

---

blocks/site/_badges.scss

Issue #262 - Fix badge panel sizes so they fit 3 on one line again for desktop view

---

config/routes.rb

Whoops, forgot fix for project votes

---

app/views/home/welcome.html.erb
app/views/ideas/index.html.erb
app/views/projects/index.html.erb
app/views/users/badges/index.html.erb
blocks/site/_base.scss
blocks/site/_bubbles.scss

Issues #316, #331, #338

---

app/views/layouts/components/_topbar.html.erb
blocks/component/_env_banner.scss
config/environments/staging.rb

closes #325.
This adds a small banner to the top of the app template which denotes which rails environment you're running (unless said environment is production).

add micro environment banner if not in production

---

app/controllers/ideas_controller.rb
app/controllers/projects_controller.rb
app/models/idea.rb
app/models/project.rb
db/migrate/20160210171523_add_missing_project_statuses.rb
db/schema.rb
db/seeds/project_statuses.rb

This unfortunately includes the foundations of the Idea/Project visibility features, because I was committing those to my master branch. However, there is no way to actually set visibility yet, so nothing should behave any differently so far. Should be safe to merge.

69 project status update

---

app/helpers/votes_helper.rb
app/models/idea_vote.rb
app/views/ideas/show.html.erb
app/views/projects/show.html.erb
app/views/shared/_editable_buttons.html.erb
app/views/shared/_support_buttons.html.erb

Issue #206 was small but the ideas/project details pages were horribly inconsistent, so I synced them up. I also moved a lot of duplicate code into a common shared view. There's still a lot of room for improvement but this should reduce our headaches a lot for now.

Issue #206

---

app/helpers/application_helper.rb
app/views/ideas/_form.html.erb
app/views/projects/_form.html.erb
blocks/bootstrap/_glyphicons.scss
blocks/bootstrap/_tooltip.scss
blocks/site/_base.scss

Also trying to reuse code more by putting tooltips in a helper.

Issue #376 - Visual fixes for form help bubbles

---

app/views/events/show.html.erb
app/views/ideas/index.html.erb
app/views/projects/index.html.erb
app/views/shared/_vote_dialog.html.erb
app/views/users/show.html.erb
blocks/bootstrap/_buttons.scss

Issue #117

---

app/controllers/auth/oauth2_controller.rb
app/controllers/ideas_controller.rb
app/controllers/projects_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/helpers/search_helper.rb
app/models/idea.rb
app/models/project.rb
app/models/user.rb
app/views/ideas/_form.html.erb
app/views/ideas/index.html.erb
app/views/ideas/show.html.erb
app/views/projects/_form.html.erb
app/views/projects/index.html.erb
app/views/projects/show.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
db/migrate/20160309000943_add_hidden_to_users.rb
db/migrate/20160309003121_remove_hidden_from_privacies.rb
db/migrate/20160309191440_remove_primary_position_from_users.rb
db/migrate/20160309201120_add_domain_to_organizations.rb
db/schema.rb
db/seeds/organizations.rb
db/seeds/users.rb
lib/rails/active_record/base.rb
test/models/privacy_test.rb
test/models/user_test.rb

Issue #410 - Multi-select for campus-specific ideas/projects

---

app/controllers/users_controller.rb
app/views/users/_form.html.erb

My commit says issue #410, that was a typo :|

Issue #415 - Add back ability for users to set their position

---

app/views/auth/local/new.html.erb
app/views/badges/_badge.html.erb
app/views/badges/index.html.erb
app/views/badges/show.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/groups/index.html.erb
app/views/home/about.html.erb
app/views/home/engagement.html.erb
app/views/ideas/index.html.erb
app/views/layouts/application.html.erb
app/views/layouts/components/_footer.html.erb
app/views/layouts/components/_topbar.html.erb
app/views/projects/index.html.erb
app/views/search/results.html.erb
app/views/shared/_nav.html.erb
blocks/bootstrap/_panels.scss
blocks/component/_engagement_meter.scss
blocks/config/_variables.scss
blocks/site/_main.scss

Fix all accessibility issues reported by WAVE on public-facing pages.

Issue #450

---

package-lock.json
package.json

Ref: https://npmjs.com/advisories/776

chore: update bower to 1.8.8
